<div class="page-header">
    <h1>
        Caterings
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["caterings/new", "Create catering"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "caterings/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <div class="col-sm-offset-0 col-sm-10">
        <?php echo $this->tag->submitButton(["Caterings list", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
