<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["caterings/index", "Go Back"]); ?></li>
            <li class="next"> <?php
                echo $this->tag->linkTo(["orders/new/" . $this->dispatcher->getParam(0), "Create"]); ?>
            </li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Orders</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-striped table-hover table-inverse table-responsive">
        <thead class="thead-inverse">
        <tr>
            <th>Priority</th>
            <th>Amount of people</th>
            <th>Cost</th>
            <th>Invoice</th>
            <th>Payed up</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $order): ?>
            <tr>
                <td><?php echo $order->getPriority() ?></td>
                <td><?php echo $order->getAmountOfPeople() ?></td>
                <td><?php echo $order->getCost() ?></td>
                <td><?php if($order->getInvoice() == 1) echo "Yes"; else echo "No"; ?></td>
                <td><?php if($order->getPayedUp() == 1) echo "Yes"; else echo "No"; ?></td>
                <td><?php echo $this->tag->linkTo(["orders/edit/" . $order->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["orders/delete/" . $order->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("caterings/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("caterings/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("caterings/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("caterings/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>