<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["caterings/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["caterings/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Caterings</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-striped table-hover table-inverse table-responsive">
        <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th>Name</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $catering): ?>
            <tr>
                <td><?php echo $catering->Id ?></td>
            <td><?php echo $catering->Name ?></td>

                <td><?php echo $this->tag->linkTo(["caterings/edit/" . $catering->Id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["caterings/delete/" . $catering->Id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("caterings/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("caterings/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("caterings/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("caterings/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>