<?php echo $this->getContent(); ?>
    <div class="page-header">
        <h1>
            Change dish
        </h1>
    </div>

<?php
echo $this->tag->form(
    [
        "dishOrders/save",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

    <div class="form-group">
        <label for="fieldDish" class="col-sm-2 control-label">Dish</label>
        <div class="col-sm-10">
            <?php
            $dishes = Dishes::find();
            echo $this->tag->select(["Dish", $dishes, "using" => ["id", "name"], "class" => "form-control", "id" => "fieldDish"])
            ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldTakeaway" class="col-sm-2 control-label">To take away</label>
        <div class="col-sm-3">
            <?php echo $this->tag->checkField(["Takeaway", "value" => "Y", "class" => "form-control", "id" => "fieldTakeaway"]) ?>
        </div>
    </div>

<?php echo $this->tag->hiddenField("OrderId") ?>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-5">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>


<?php echo $this->tag->endForm(); ?>