<div class="page-header">
    <h1>
        Date
    </h1>
</div>


<div class="form-group">
    <label for="fieldStartTime" class="col-sm-2 control-label">Start time</label>
    <div class="col-sm-3">
        <?php echo $this->tag->dateTimeField(["StartTime", "class" => "form-control", "id" => "fieldStartTime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEndTime" class="col-sm-2 control-label">End time</label>
    <div class="col-sm-3">
        <?php echo $this->tag->dateTimeField(["EndTime", "class" => "form-control", "id" => "fieldEndTime"]) ?>
    </div>
</div>



