<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="https://www.circuscircus.com/content/dam/MGM/circus-circus-las-vegas/meetings/circus-circus-meetings-groups-caterings.jpg" alt="Caterings">
            <div class="carousel-caption">
                <h3>Caterings</h3>
                <p>We prepare catering with the most yummy food you have ever eaten</p>
            </div>
        </div>

        <div class="item">
            <img src="http://softboot.net/images/softboot/clients.jpg" alt="Clients">
            <div class="carousel-caption">
                <h3></h3>
                <p></p>
            </div>
        </div>

        <div class="item">
            <img src="https://upload.wikimedia.org/wikipedia/commons/e/e6/Veggie_pizza.jpg" alt="Dishes">
            <div class="carousel-caption">
                <h3>Dishes</h3>
                <p>Dishes we serve and their ingredients</p>
            </div>
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
