<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header navbar-brand">
        <?php echo Phalcon\Tag::linkTo("index", "Caterings managment"); ?>    
    </div>
    <ul class="nav navbar-nav">

      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <?php 
          $auth = $this->session->get("auth");
          if (!$auth) {
            echo Phalcon\Tag::linkTo("users/new", "Sign up");
          }
        ?>
      </li>
      <li>
        <?php 
          $auth = $this->session->get("auth");
          if (!$auth) {
            echo Phalcon\Tag::linkTo("session/", "Login");
          }
        ?>
      </li>
      <li>
        <?php 
          $auth = $this->session->get("auth");
          if ($auth) {
            echo Phalcon\Tag::linkTo("session/logout", "Log out");
          }
        ?>
      </li>
    </ul>
  </div>
</nav>