<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Caterings managment</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <?php 
          $auth = $this->session->get("auth");
          if (!$auth) {
            echo Phalcon\Tag::linkTo("users/new", "Sign up");
          }
        ?>
      </li>
      <li>
        <?php 
          $auth = $this->session->get("auth");
          if (!$auth) {
            echo Phalcon\Tag::linkTo("session/", "Login");
          }
        ?>
      </li>
      <li>
        <?php 
          $auth = $this->session->get("auth");
          if ($auth) {
            echo Phalcon\Tag::linkTo("session/logout", "Log out");
          }
        ?>
      </li>
      <!-- <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Login</a></li> -->
    </ul>
  </div>
</nav>