<nav class="navbar navbar-inverse">
<div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="~/index">Caterings managment</a>
    </div>
    <ul class="nav navbar-nav">
      <li><?php echo Phalcon\Tag::linkTo("index", "Home"); ?></li>
      <li><?php echo Phalcon\Tag::linkTo("caterings", "Caterings"); ?></li>
      <li><?php echo Phalcon\Tag::linkTo("clients", "Clients"); ?></li>
      <li><?php echo Phalcon\Tag::linkTo("dishes", "Dishes"); ?></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <?php 
          $auth = $this->session->get("auth");
          if (!$auth) {
            echo Phalcon\Tag::linkTo("users/new", "Sign up");
          }
        ?>
      </li>
      <li>
        <?php 
          $auth = $this->session->get("auth");
          if (!$auth) {
            echo Phalcon\Tag::linkTo("session/", "Login");
          }
        ?>
      </li>
      <li>
        <?php 
          $auth = $this->session->get("auth");
          if ($auth) {
            echo Phalcon\Tag::linkTo("session/logout", "Log out");
          }
        ?>
      </li>
    </ul>
  </div>
</nav>