<h1>
    Client details
</h1></br></br>

<h4>
    <dl class="dl-horizontal">
        <dt>First name</dt>
        <dd><?php
            echo Clients::findFirst($this->dispatcher->getParam(0))->getFirstName();
        ?></dd>
        <dt>Last name</dt>
        <dd><?php
            echo Clients::findFirst($this->dispatcher->getParam(0))->getLastName();
        ?></dd>
        <dt>Phone</dt>
        <dd><?php
            echo Clients::findFirst($this->dispatcher->getParam(0))->getContactData()[0]->getPhone();
        ?></dd>
        <dt>Email</dt>
        <dd><?php
            echo Clients::findFirst($this->dispatcher->getParam(0))->getContactData()[0]->getEmail();
        ?></dd>
        <dt>Fax</dt>
        <dd><?php
            echo Clients::findFirst($this->dispatcher->getParam(0))->getContactData()[0]->getFax();
        ?></dd>
        <dt>Places</dt>
        <dd><?php
            echo $this->tag->linkTo(["clients/placesList/" . Clients::findFirst($this->dispatcher->getParam(0))->getId(), "List"]);
        ?></dd>
    </dl>
</h4>