<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

    <div class="page-header">
        <h1>
            Clients
        </h1>
        <p>
            <?php echo $this->tag->linkTo(["clients/new", "Create clients"]) ?>
        </p>
        <p>
            <?php echo $this->tag->linkTo(["clients/list", "List all clients"]) ?>
        </p>
    </div>

<?php echo $this->getContent() ?>

<?php
echo $this->tag->form(
    [
        "clients/search",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

    <div class="form-group">
        <label for="fieldId" class="col-sm-2 control-label">Id</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["Id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldFirstName" class="col-sm-2 control-label">First name</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldLastName" class="col-sm-2 control-label">Last name</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>

<?php echo $this->tag->endForm(); ?>