<div class="page-header">
    <h1>
        Create
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    [
        "clients/create",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<div class="form-group">
    <label for="fieldFirstName" class="col-sm-2 control-label">First Name</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastName" class="col-sm-2 control-label">Last Name</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
    </div>
</div>

<?php $this->partial("contactDatas/new"); ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-5">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>