<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["clients/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["clients/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Clients</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-striped table-hover table-inverse table-responsive">
        <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $client): ?>
            <tr>
                <td><?php echo $client->getId() ?></td>
                <td><?php echo $client->getFirstName() ?></td>
                <td><?php echo $client->getLastName() ?></td>
                <td><?php echo $this->tag->linkTo(["clients/placesList/" . $client->getId(), "Places"]); ?></td>
                <td><?php echo $this->tag->linkTo(["clients/details/" . $client->getId(), "Details"]); ?></td>
                <td><?php echo $this->tag->linkTo(["clients/edit/" . $client->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["clients/delete/" . $client->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("caterings/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("caterings/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("caterings/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("caterings/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>