<?php echo $this->getContent(); ?>
    <div class="page-header">
        <h1>
            Choose place
        </h1>
    </div>

<?php
echo $this->tag->form(
    [
        "orders/choosePlace",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<div class="form-group">
    <label for="fieldPlace" class="col-sm-2 control-label">Place</label>
    <div class="col-sm-10">
        <?php
            $order = Orders::findFirst($this->dispatcher->getParam(0));
            $clientId = $order->getClientId();
            $places = Places::find(["clientId = :clientId:", "bind" => ["clientId" => $clientId]]);
            echo $this->tag->select(["Place", $places , "using" => ["id", "address"], "class" => "form-control", "id" => "fieldPlace"])
        ?>
    </div>
</div>
<?php echo $this->tag->hiddenField("OrderId") ?>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-5">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>


<?php echo $this->tag->endForm(); ?>