<div class="page-header">
    <h1>
        Create Dish
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    [
        "dishes/create",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<div class="form-group">
    <label for="fieldDishName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["DishName", "size" => 30, "class" => "form-control", "id" => "fieldDishName"]) ?>
    </div>
</div>

<?php $this->partial("ingredients/new"); ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-5">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>