<div class="page-header">
    <h1>
        Contact Data
    </h1>
</div>


<div class="form-group">
    <label for="fieldPhone" class="col-sm-2 control-label">Phone Number</label>
    <div class="col-sm-3">
        <?php echo $this->tag->telField(["Phone", "class" => "form-control", "id" => "fieldPhone"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-3">
        <?php echo $this->tag->emailField(["Email", "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFax" class="col-sm-2 control-label">Fax</label>
    <div class="col-sm-3">
        <?php echo $this->tag->telField(["Fax", "class" => "form-control", "id" => "fieldFax"]) ?>
    </div>
</div>



